"""third migration

Revision ID: 50f97b9155f8
Revises: 82f56624f030
Create Date: 2025-01-24 15:36:28.060298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50f97b9155f8'
down_revision = '82f56624f030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phonenumber', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('residence', sa.String(length=100), nullable=False),
    sa.Column('Admin_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Admin_id'], ['pastor.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('residence'),
    sa.UniqueConstraint('role')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.Text(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
        batch_op.drop_constraint('user_residence_key', type_='unique')
        batch_op.drop_constraint('user_Admin_id_fkey', type_='foreignkey')
        batch_op.drop_column('Admin_id')
        batch_op.drop_column('residence')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('residence', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('Admin_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('user_Admin_id_fkey', 'pastor', ['Admin_id'], ['id'], ondelete='CASCADE')
        batch_op.create_unique_constraint('user_residence_key', ['residence'])
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('password_hash')

    op.drop_table('member')
    # ### end Alembic commands ###
