"""second migration

Revision ID: 82f56624f030
Revises: 07b4aad672ee
Create Date: 2025-01-24 14:19:21.604627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82f56624f030'
down_revision = '07b4aad672ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Admin_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'pastor', ['Admin_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('Admin_id')

    # ### end Alembic commands ###
