"""nineth  migration

Revision ID: 9f3b4da004d1
Revises: 16958f0e3d63
Create Date: 2025-01-25 23:14:16.154515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f3b4da004d1'
down_revision = '16958f0e3d63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_id', sa.Integer(), nullable=False))
        batch_op.alter_column('phonenumber',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=15),
               existing_nullable=False)
        batch_op.drop_constraint('member_role_key', type_='unique')
        batch_op.drop_constraint('member_Admin_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'pastor', ['admin_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('Admin_id')

    with op.batch_alter_table('pastor', schema=None) as batch_op:
        batch_op.alter_column('phonenumber',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=15),
               existing_nullable=False)
        batch_op.drop_constraint('pastor_role_key', type_='unique')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('phonenumber',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=15),
               existing_nullable=False)
        batch_op.drop_constraint('user_role_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint('user_role_key', ['role'])
        batch_op.alter_column('phonenumber',
               existing_type=sa.String(length=15),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('pastor', schema=None) as batch_op:
        batch_op.create_unique_constraint('pastor_role_key', ['role'])
        batch_op.alter_column('phonenumber',
               existing_type=sa.String(length=15),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('member', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Admin_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('member_Admin_id_fkey', 'pastor', ['Admin_id'], ['id'], ondelete='CASCADE')
        batch_op.create_unique_constraint('member_role_key', ['role'])
        batch_op.alter_column('phonenumber',
               existing_type=sa.String(length=15),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.drop_column('admin_id')

    # ### end Alembic commands ###
